name: Function test

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
  
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.12
        architecture: x64
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r "requirements.txt"
    - name: Run pruning function test script
      run: |
        python src/test/pruning_function_test.py
