name: Function Test

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.10'
        auto-activate-base: false
        activate-environment: myenv
        use-mamba: true
    - name: Install Dependencies
      run: |
        conda install -y pip
        pip install -r requirements.txt
    - name: Run Pruning Function Test Script
      run: |
        python src/test/pruning_function_test.py
