name: Funktionstest

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Setze Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Installiere Abhängigkeiten
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Führe Pruning-Funktionstest aus
      run: |
        python src/test/pruning_function_test.py
